#!/bin/bash

# make package build directory not tempfs because it is a massive install 
mkdir $HOME/.cache/packages
sudo sed -i "s+^#BUILDDIR=.*+BUILDDIR=$HOME/.cache/packages+" /etc/makepkg.conf

# Clone nerd fonts, cd into it, remove iosevka conflict, and build package
git clone --depth 1 https://github.com/ryanoasis/nerd-fonts $HOME/nerd-fonts-complete

cd $HOME/nerd-fonts-complete
./install.sh
cd $HOME
rm -rf $HOME/nerd-fonts-complete/

cd $HOME/nescafe-dotfiles
git submodule init
git submodule update --remote --merge

paru -S $(grep -Ev '^#|^$' $HOME/nescafe-dotfiles/packagelist.txt) --needed --noconfirm --noremovemake --batchinstall 

mkdir -p $HOME/.local/share/fonts XDG_DATA_HOME XDG_CACHE_HOME XDG_CONFIG_HOME GEM_PATH GEM_SPEC_CACHE NPM_CONFIG_USERCONFIG GNUPGHOME _JAVA_OPTIONS GTK2_RC_FILES ZDOTDIR CARGO_HOME FFF_TRASH GEM_HOME GOPATH NPM_CONFIG_USERCONFIG NPM_PACKAGES NODE_PATH $HOME/.cargo/bin $HOME/.local.bin XDG_CONFIG_HOME XDG_CACHE_HOME XDG_DATA_HOME XDG_STATE_HOME XDG_CONFIG_DIRS XDG_DATA_DIRS XDG_RUNTIME_DIR XDG_DESKTOP_DIR XDG_DOWNLOAD_DIR XDG_TEMPLATES_DIR XDG_PUBLICSHARE_DIR XDG_DOCUMENTS_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_VIDEOS_DIR FFF_TRASH MANPATH INFOPATH GNUPGHOME GTK2_RC_FILES

cp -v $HOME/nescafe-dotfiles/.zshenv $HOME/
source $HOME/.zshenv
source $HOME/.config/zsh/.zshrc

cp -rv $HOME/nescafe-dotfiles/fonts/* $HOME/.local/share/fonts
fc-cache -fv

cp -rv $HOME/nescafe-dotfiles/config/* $HOME/.config

cp -v $HOME/nescafe-dotfiles/.Xresources $HOME/

sudo cp -rf $HOME/nescafe-dotfiles/themes/gtk/Aesthetic-Night/* /usr/share/themes

sudo cp -rv $HOME/nescafe-dotfiles/lightdm/* /etc/lightdm/
sudo systemctl enable lightdm.service
