#!/bin/bash
username="$(whoami)"

# make package build directory not tempfs because it is a massive install 
mkdir /home/$username/.cache/packages
sudo sed -i "s+^#BUILDDIR=.*+BUILDDIR=$HOME/.cache/packages+" /etc/makepkg.conf

# Clone nerd fonts, cd into it, remove iosevka conflict, and build package
git clone --depth 1 https://github.com/ryanoasis/nerd-fonts /home/$username/nerd-fonts-complete

cd /home/$username/nerd-fonts-complete
makepkg -si
cd /home/$username
rm -rf /home/$username/nerd-fonts-complete

cd /home/$username/nescafe-dotfiles
git submodule update --remote --merge

paru -S $(grep -Ev '^#|^$' nescafe-dotfiles/packagelist.txt) --needed --noconfirm 

cp .zshenv /home/$username/
source /home/$username/.zshenv
source /home/$username/.config/zsh/.zshenv


mkdir -p /home/$username/.local/share/fonts XDG_DATA_HOME XDG_CACHE_HOME XDG_CONFIG_HOME GEM_PATH GEM_SPEC_CACHE NPM_CONFIG_USERCONFIG GNUPGHOME _JAVA_OPTIONS GTK2_RC_FILES ZDOTDIR CARGO_HOME FFF_TRASH GEM_HOME GOPATH NPM_CONFIG_USERCONFIG NPM_PACKAGES NODE_PATH $HOME/.cargo/bin $HOME/.local.bin XDG_CONFIG_HOME XDG_CACHE_HOME XDG_DATA_HOME XDG_STATE_HOME XDG_CONFIG_DIRS XDG_DATA_DIRS XDG_RUNTIME_DIR XDG_DESKTOP_DIR XDG_DOWNLOAD_DIR XDG_TEMPLATES_DIR XDG_PUBLICSHARE_DIR XDG_DOCUMENTS_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_VIDEOS_DIR FFF_TRASH MANPATH INFOPATH GNUPGHOME GTK2_RC_FILES

sudo cp -r lightdm /etc/lightdm

cp -r fonts/* /home/$username/local/share/fonts
fc-cache -fv

cp -r nescafe-dotfiles/.config/* /home/$username/.config

cp .Xresources /home/$username/
